QHttpServerRequest: Fix GCC's -Wmaybe-uninitialized
GCC complains that `state` may contain an unenumerated value and
therefore `read` may be used uninitialized:

  qhttpserverrequest.cpp: In member function ‘bool QHttpServerRequestPrivate::parse(QAbstractSocket*)’:
  qhttpserverrequest.cpp:297:21: error: ‘read’ may be used uninitialized [-Werror=maybe-uninitialized]
    297 |     return read != -1;
        |                     ^
  qhttpserverrequest.cpp:266:15: note: ‘read’ was declared here
    266 |     qsizetype read;
        |               ^~~~

Fix by inserting a strategic Q_UNREACHABLE(). Do so without a default:
case which would break -Wswitch warning about unhandled enum values.

Task-number: QTBUG-100868
Change-Id: If9514c676f3e927fd748781147f2c02e5ca35d4c
Reviewed-by: Jesus Fernandez <jsfdez@gmail.com>
(cherry picked from commit 6d015dea840f643550742496ec1b669c54a87755)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>